<figure> 
<img src="../Imagenes/logo-final-ap.png"  width="80" height="80" align="left"/> 
</figure>

# <span style="color:blue"><left>Aprendizaje Profundo</left></span>

# <span style="color:red"><center>Minicurso  de Inteligencia Artificial<center></span>

## <span style="color:Green"><center>Introducción a Python<center></span>

##   <span style="color:blue">Profesores</span>

1. Alvaro  Montenegro, PhD, ammontenegrod@unal.edu.co
2. Daniel  Montenegro, Msc, dextronomo@gmail.com 
1. Oleg Jarma, Estadístico, ojarmam@unal.edu.co 

##   <span style="color:blue">Asesora Medios y Marketing digital</span>
 

4. Maria del Pilar Montenegro, pmontenegro88@gmail.com 

## <span style="color:blue">Contenido</span>

* ¿Qué es python?
* Colecciones
* Numpy
* pandas
* procesamiento paralelo

##  <span style="color:blue">¿Qué es Python?</span>

![Logo Python](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)



Python es un lenguaje de programación (¿Qué es un programa?) popular que se usa normalmente para:

* Desarrollo web en servidores,
* Desarrollo de Software,
* Cálculos Matemáticos,
* Desarrollo de Scripts.

## <span style="color:blue">¿Qué puede hacer Python?</span>

* Puede ser usado en un servidor para crear **aplicaciones web**,
* Puede conectarse a sistemas de **bases de datos**. Puede leer y modificar archivos.
* Puede ser usado para manejar **Big Data** y hacer cálculos matemáticos de alta complejidad.
* **Prototipo rápido** para producción de Software.

[[Volver al inicio]](#Contenido)

## <span style="color:blue">¿Por qué Python?</span>

* Funciona en diferentes **plataformas** (Windows, Mac, Linux, etc).
* Tiene una **sintaxis** (forma de escribir) simple, similar al idioma inglés.
* Tiene una sintáxis que permite escribir programas en **muy pocas líneas**, comparado con otros lenguajes de programación.
* Pyhton se ejecuta en un **sistema interpretado**. Es decir, que los códigos se pueden correr **justo después de ser escritos**; en otras palabras, no necesitan compilación previa.
* Se puede usar como un lenguaje **clásico**, como un lenguaje **orientado a objetos**, o como un lenguaje **funcional**.
* Es el principal lenguaje de la **Ciencia de Datos**.

[[Volver al inicio]](#Contenido)

## <span style="color:blue">Hello World!</span>

El primer ejemplo clásico de programación es saludar, o sea, decirle al computador que muestre un saludo. Para esto, se usa la función de Python llamada **print**. Para colocar un saludo (o un **texto cualquiera**), se debe colocar entre **comillas dobles o sencillas** dentro del comando print. Entonces, para que el computador muestre un saludo, por ejemplo **Hello, World!**, debemos escribir en ambiente de código como sigue


In [1]:
print('Hello friend. Hello friend?')

Hello friend. Hello friend?


##   <span style="color:blue">Variables en Python</span>

Una variable sirve para **guardar un valor específico**, ya sea **numérico**, **texto** u otro **tipo de Dato** con el nombre con la que se nombre dicha variable. Observe el siguiente ejemplo.

In [2]:
# Asignamos 1 a la variable x

x = 1

print("El valor de la variable x es", x)

# Asignamos "¡Vamos a programar!" a la variable y

y = "¡Vamos a programar!"

print("\nEl valor de la variable y es", y)

El valor de la variable x es 1

El valor de la variable y es ¡Vamos a programar!


[[Volver al inicio]](#Contenido)

##   <span style="color:blue">Asignación dinámica en Python</span>

En Python, como en R, Julia, Matlab y otros lenguajes no es necesario declarar una variable de antemano, como ocurre en otros lenguajes como C, C++ y muchos otros lenguajes de bajo nivel. 
La asignación dińamica implica que es posible cambiar el tipo de dato de una variable con tan solo reasignarle un valor. En Python, se delega al programador la responsabilidad de cuidarse de efectos no esperados al cambiar el tipo de una variable. Vea el sigueinte ejemplo.

In [3]:
x = 5.6
print('x es número un real:', x)

x = 3+4j
print('x es ahora un número complejo:', x)

x = '25 de mayo'
print('En cambio ahora x es un string:', x)

x es número un real: 5.6
x es ahora un número complejo: (3+4j)
En cambio ahora x es un string: 25 de mayo


[[Volver al inicio]](#Contenido)

##   <span style="color:blue">Reglas para la creación de variables</span>

* El nombre de una variable **debe comenzar** con una letra ó con _.
* El nombre de una variable **no puede comenzar** con un número.
* El nombre de una variable **sólo puede contener** carácteres alfa-numéricos.
* El nombre de una variable tiene **sensibilidad** a **mayúsculas** y **minúsculas** (x es diferente de X).

##  <span style="color:blue">Tipos de datos básicos en Python</span>

###  <span style="color:blue">Enteros (int)</span>

Vea el siguiente ejemplo

In [4]:
x = 1
print(x)
print(type(x))
x = 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
print(x)
print(type(x))

1
<class 'int'>
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
<class 'int'>


Se observan dos cosas interesantes. Primero, el tipo de dato es una clase 'int'. Todo en Pyhon son objetos, incluidos la variables simples. En otro cuaderno estudiaremos las clases y objetos en detalle. 

Segundo, En pyhton puede tener números enteros tan grandes como desee, a diferencia de otros lenguajes. de otros lenguajes.

###  <span style="color:blue">Punto Flotante (float)</span>

Lo número reales son representados usando el estándar IEEE 754 double precision.

In [5]:
x = 1.56
print(x)
print(type(x))

1.56
<class 'float'>


###  <span style="color:blue">Números complejos (complex)</span>

Se representan en la forma $a + bj$, en donde $a$ es la parte real y $ b$ la parte imaginaria

In [6]:
z = 3.4 + 4j
print(z)
print(type(z))

(3.4+4j)
<class 'complex'>


###  <span style="color:blue">Booleanas (bool)</span>

El tipo booleano se utiliza para variables que solamente pueden ser 'True' o 'False', es decir, valores booleanos o lógicos. Por ejemplo:

In [7]:
t = True 
print(t)
print(type(t))

True
<class 'bool'>


###  <span style="color:blue">None</span>

Este es un tipo especial de dato utilizado para indicar que una determinada variable no contiene ningún dato. Es muy útil en el control de muchas situaciones, porque sirve para saber si algún objeto a llegado a ser None. Mire el siguiente ejemplo.

In [8]:
b = None
print(b)
print(type(b))

z = 5

b is None


None
<class 'NoneType'>


True

###  <span style="color:blue"> Textos: strings</span>


Los string son expresiones que representan una cadena de caracteres, útiles para escribir mensajes y combinarlos con valores que generemos en nuestros procesamientos. Para escribir un texto en Python usamos comillas simples: `'...'` o comillas dobles: `"..."`. Combinamos comillas para poner comillas adentro:

Como vimos, la función print es la que nos permite imprimir estos mensajes. El texto \n indica una nueva linea en el texto:

In [9]:
print("Una línea\nOtra línea")

Una línea
Otra línea


Podemos recorrer los valores de la cadena de texto de la siguiente forma:

In [10]:
texto="cuidado_con_el_orden"
texto

'cuidado_con_el_orden'

Extrayendo el elemento cero del texto (**primer caracter**):

In [11]:
print(texto[0])

c


Extrayendo el elemento uno del texto (**segundo caracter**):

In [12]:
texto[1]

'u'

Extrayendo el elemento cinco hasta el elemento 9 del texto (**sin incluir el 9**):

In [13]:
texto[5:9]

'do_c'

**También se pueden usar índices negativos** (Python exclusive):

In [14]:
texto[3:-1]

'dado_con_el_orde'

In [15]:
texto[-1]

'n'

## <span style="color:blue">Suma de variables y concatenación de variables</span>

Python es tan sencillo e intuitivo, que es posible sumar diferentes variables y sumarlas con el símbolo **+**. Cuando las variables son numéricas, se **suman matemáticamente** y cuando es texto se **concatenan**.

In [16]:
# Sumar dos textos

x = "Python is "; 
y = "awesome";
z =  x + str(y);
print(z);

# Sumar dos números

n1 = 1;
n2 = 5;
suma = n1 + n2;
print(suma);

# Escribir texto y números
print(x+"the number",n1);

Python is awesome
6
Python is the number 1


## <span style="color:blue">Operadores Aritméticos y redondeo</span>

La fortuna de que Python reconozca variables numéricas nos permite usarla como una calculadora simple, podemos ejecutar operaciones muy sencillas teniendo en cuenta la siguiente tabla:

| **Operador** | **Descripción** |
| :---: | :---: |
|`+`|Suma|
|`-`|Resta|
|`*`|Multiplicación|
|`/`|División|
|`**`|Potencia|


### Ejemplo 

 Si queremos operar:
 
 $$ 5\times(3-5)^2-\cfrac{6}{(9)^{1/2}}$$
 
 tenemos que escribir:

In [17]:
5*(3-5)**2-(6)/(9**(1/2))

18.0

### <span style="color:blue"> Divsión y residuo entre enteros</span>

La división es una operación bien especial pues la mayoría de ocasiones produce un número con parte fraccionaria. Sin embargo, cuando estábamos pequeños nos enseñaron a dividir enteros dando como respuesta un entero llamado cociente y lo que hacia falta para completar la división, un número llamado residuo. En Python podemos calcular esos valores con `\\` para el cociente y `%`para el residuo. Por ejemplo, sabemos que:

$$ 20 \div 3 = 6 \ \ \ \text{ con residuo } 2$$
tenemos:

In [18]:
20//3

6

In [19]:
20%3

2

Finalmente, una función elemental y útil para el tratamiento de números decimales es `round`. Lo usamos para redondear los valores a uno con el decimal que escojamos. Tenemos:

In [20]:
n1=47/3
n1

15.666666666666666

In [21]:
n2=round(n1)
n2

16

In [22]:
n3=round(n1,3)
n3

15.667

## <span style="color:blue">Estructuras de control</span>

En cualquier lenguaje de programación existen tres estructuras de control básicas que corresponden a 

- Secuencia
- Selección (o decisión)
- Iteración (repetición)

### Secuencia

La ejecución de cualquier programa (algoritmo codificado en algún lenguaje de programación) se realiza en orden de aparición de las sentencias. Una **sentencia** puede ser **simple** (solamente una instrucción) o **compuesta** (varias instrucciones).

#### Ejemplo

Observe el siguiente código Python

In [23]:
x = 1; 
y = 2;

print(x,y)

1 2


En el ejemplo hay tres sentencias. Dos sentencias de asignación de valores y una sentencia de impresión. Se ejecuta una después de la otra.

### Selección (if)

Esta estructura de control está diseñada para que un programa pueda seguir diferentes caminos de ejecución, dependiendo de la evaluación de una expresión lógica. Observe el siguiente ejemplo.

In [24]:
# ejemplo if
x = 5
y = 3

if x>y:
    print("Cinco es mayor que Tres")
    print("lunes")

Cinco es mayor que Tres
lunes


La estructura empieza con la palabra clave **if**. Luego aparece una condición lógica que es evaluada (x>y). Si la condición es verdadera, como en este caso, se ejecutan las instrucciones escritas dentro de la estructura.

### <span style="color:blue">Operadores de comparación</span>

| **Operador** | **Descripción** |**Ejemplo**|
| :---: | :---: |:---: |
|`==`|Prueba si dos valores son iguales| 3==3|
|`!=`|Prueba si dos valores no son iguales entren si| 2!=3|
|`<`|Prueba si el valor de la izquierza es menor que el de la derecha|4<3|
|`>`|Prueba si el valor de la izquierza es mayor que el de la derecha|4<3|
|`<=`|Prueba si el valor de la izquierza es menor o igual que el de la derecha|4<=3|
|`>=`|Prueba si el valor de la izquierza es mayor igual que el de la derecha|4<=3|

### <span style="color:blue">Operadores Lógicos</span>

| **Operador** | **Descripción** |**Ejemplo**|
| :---: | :---: |:---: |
|`and`|Regresa verdadero si el valor de las izquierda y el de la derecha son verdaderos| (3<4) and (5>1)|
|`or`|Regresa verdadero si uno de los dos valores a(izquierda o derecha es verdadero, o ambos| (3<4) or (5<1)|
|`not`|Regresa verdadero si el valor que se esta evaluado es falso|not 3>2|

## <span style="color:blue">Estructura de repetición [ciclos]</span>

Este tercer tipo de estructura de control se usa para los casos en los cuales es necesario correr un proceso varas veces en forma continua.

### Ciclo while

Al comienzo del ciclo se evalúa una condición. Si la condición es verdadera se ejecuta de nuevo el ciclo. En otro caso, termina. Corra y analice el siguiente fragmento (snippet) de código

In [25]:
contador = 0

print('Starting')
while contador < 10:
    #Instrucciones útiles
    print(contador,' ', end='')
    contador = contador + 1
    
print()
print('Done')

Starting
0  1  2  3  4  5  6  7  8  9  
Done


### Ciclo for

En este caso se usa una variable de salto que va recorriendo un conjunto de valores hasta terminar. Revise el siguiente snippet.

In [26]:
print('\nStart:')
for i in range(20):
    # Instrucciones útiles
    print(i, ' ', end='')

print('\nDone.')


Start:
0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  
Done.


### Break

Se usa para terminar la ejecución de un ciclo while o for. Corra el siguiente ejemplo dadno difentes valores.

In [27]:
for  i in range(10):
    print(i)
    if i==5:
        break

0
1
2
3
4
5


## <span style="color:blue">Estructuras de control anidadas</span>

Es posible incluir (o anidar) estructuras de control dentro de otras estructuras de control.

Esto es de gran utilidad para realizar programas de mayor complejidad.

**Ejemplo:**

In [28]:
x = 5
y = 3
print(x,y)

5 3


In [29]:
if x>y:
    print("Cinco es mayor que tres")
    for i in range(5):
        print(i)
    x = 9.9

y = 2
print(x, y)

Cinco es mayor que tres
0
1
2
3
4
9.9 2


### Ciclos anidados

In [30]:
for i in range(0,11):             #line 1
    for j in range(i):            #line 2
        print('*', end='')        #line 3
    print('')                     #line 4c


*
**
***
****
*****
******
*******
********
*********
**********


## <span style="color:blue">Funciones en Python</span> 

Para entender funciones en Python (Paquetes dentro de módulos de Python), debemos pensar en actos reales para poder hacer una **analogía** en el ambiente de programación.

Imagínese cuando se levanta.

Lo que ocurre primero, es que uno se siente vivo, se abren los ojos (no siempre), se hace pereza un rato, se levanta de la cama y luego se inicia el día (cada persona tiene sus maneras diferentes de lograrlo).

Esta serie de **pasos consecutivos** conforman lo que se llama una **función**.

En el común, una **función es en realidad una acción** o una serie de acciones que generan un resultado a través de un proceso intermedio.

Para poder distinguir funciones, unas de otras, se le dan dotado de nombres diferentes.

Por ejemplo, la función antes descrita podría nombrarse como **Levantarse**:

Está función se compone de los siguientes pasos:

1. **Sentirse vivo.**
2. **Abrir los ojos.**
3. **Hacer pereza.**
4. **Levantarse.**

En el lenguaje de programación, ésto se podría escribir como

```Levantarse(x)```

donde $x$ representa el individuo que hace la acción y los paréntesis significan que se habla de una función, y por lo tanto, **no se confunde** con una variable.

### Creación de Funciones

Es posible crear funciones para generar rutinas específicas.

Hay dos maneras de generar funciones en Python:

1. **def**
2. **lambda**

**Ejemplo:**

In [31]:
# Explicar las siguientes líneas de código
def mysum_prod(x,y):
    s=x+y
    p=x*y
    return s,p

In [32]:
suma, prod = mysum_prod(3,4)
print("El suma es:", suma)
print("El producto es:", prod)

El suma es: 7
El producto es: 12


In [33]:
# Explique qué diferencias hay entre éste método y el anterior

sumita = lambda arg1,arg2: arg1+arg2

a=6
b=65
s = sumita(a,b)
print("la suma es:", s)

la suma es: 71


# <span style="color:red"><center> Listas, Tuplas y Diccionarios en Python</center></span>

Una colección es un contenedor de objetos del mismo tipo. Por defecto en Python existen cuatro tipos de contenedores:

- **Listas (list).** Son colecciones de objetos que están ordenado y son mutables, es decir, sus contenidos pueden ser modificados. Los elementos son indexados y permite duplicados.

- **Tuplas (tuple).** Esta es una colección de objetos que están ordenados y son inmutables (no pueden modificarse). Las tuplas admiten elementos repetidos y sus miembros son indexados.

- **Diccionarios (dictionary)** Son contendores no ordenados, que son indexados mediante una clave, la cual referencia a un valor. El valor es retornado cuando se le solicita con la clave. No se admiten claves repetidas, pero si valores repetidos.

Recuerde que todo en Python es realmente un tipo de objeto.

## <span style="color:blue">Listas</span>

Las listas son contenedores mutables y ordenados de objetos. Las listas se distingen porque sus elementos están encerrados entre paréntesis cuadrados. Por ejemplo:

In [34]:
lista1 = ['Alvaro', 'Daniel', 'Pilar', 'Beatriz']

for i in lista1:
    print(i, end=' ')
print('')

Alvaro Daniel Pilar Beatriz 


## <span style="color:blue">Tuplas</span>

Las tuplas se crean y se reconocen porque los elementos se escriben entre paréntesis circulares: '()'. Por ejemplo tupla1 en la siguiente línea define una tupla.

In [35]:
tupla1 = (1,3,5,7)

Cada elemento de la tupla está indexado. Por ejemplo, discuta el siguiente snippet de código.

In [36]:
print ('Acceso a la tupla con iterator')
for i in tupla1:
    print(i)

print('Acceso al tupla con índices')
for i in range(len(tupla1)):
    print(i, tupla1[i] )

Acceso a la tupla con iterator
1
3
5
7
Acceso al tupla con índices
0 1
1 3
2 5
3 7


#### Constructor de tuplas: tuple(iterable)

Una tupla puede crearse a partir de cualquier objeto iterable. Por ejemplo:

In [37]:
lista1 = [1,2,3]
tupla2 = tuple(lista1)
print(tupla2)

(1, 2, 3)


Observe como los valores de la lista pueden modificarse pero no los de la tupla

Las tuplas pueden contener diferentes tipos.
Por ejemplo en el siguiente fragmento *tup2* es una tupla que contiene un entero, un string, un tupla y un float.

In [38]:
tup2 = (1,"John", tupla1, True, -23.1)

for i in tup2:
    print(i)

1
John
(1, 3, 5, 7)
True
-23.1


### Listas de listas y listas de tuplas

Una lista puede contener objetos muy complejos. Por ejemplo observe detenidamente la siguiente construcción.

In [39]:
t1 = (1, 'Oleg', 24.5)
l1 = ['Maria', 'Bonita']
l2 = [t1, l1]
t2 = (l2,'manzana')

print('t1=', t1)
print('l1=', l1)
print('l2=', l2)
print('t2=', t2)

t1= (1, 'Oleg', 24.5)
l1= ['Maria', 'Bonita']
l2= [(1, 'Oleg', 24.5), ['Maria', 'Bonita']]
t2= ([(1, 'Oleg', 24.5), ['Maria', 'Bonita']], 'manzana')


## Funciones útiles de las listas

### Adicionar elementos a una lista

`lista.append(objeto)`

In [42]:
alfabeto = 'abcdefghijklmnñopqrstuvwxyz'
print( 'alfabeto es un objeto string: ',type(alfabeto))

alfabeto es un objeto string:  <class 'str'>


Vamos a crear una lista vacia y la vamos a llenar con cada uno de los elementos de *alpfabeto*

In [43]:
alfaL = []

for i in alfabeto:
    alfaL.append(i)

print(alfaL)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


### Concatenar dos listas

In [127]:
N = len(alfaL)

numL = []

for i in range(N):
    numL.append(i)

print('alfaL = ',alfaL) 
print('\n')
print('numL = ',numL)
print('\n')

alfanumL = alfaL + numL

print('alfanumL = ',alfanumL) 

alfaL =  ['a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


numL =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


alfanumL =  ['a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


### Eliminar elementos de una lista

`lista.remove(objeto)`

In [45]:
alfaL.remove('c')
print(alfaL)

['a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


### Métodos para manipulación de listas

|Method| Description|
|---|---|
|append()| Agrega un elemento al final de la lista|
|clear()| Remueve todo los elementos de la lista|
|copy()| Regresa una copia de la lista|
|count()| Regresa el número de elementos con el valor especificado|
|extend()| Agrega elementos de una lista (o cualquier iterable) al final de esta lista|
|index()|Regresa el índice del primer elemento con el valor especificado|
|insert()|  Addiciona un elemento en la posición especificada|
|pop()| Remueve un elemento en la posición especificada y puede retornarlo si se hce una asignación|
|remove()| Remueve el item con este valor específico|
|reverse()| Invierte el orden de la lista|
|sort() | Ordena la lista|


Por favor pruebe cada uno de estos métodos. Veamos unos pocos ejemplos.

## <span style="color:blue">Diccionarios </span>

Los diccionarios se distinguen por dos conceptos claves: están encapsulado en {} y poseeen el concepto de llave e ítem.

**Consideraciones importantes:**

En **contraste con las listas**, los elementos del diccionario no se acceden vía índices, sino vía llaves (**keys**) que se definen.

Miremos el siguiente ejemplo:

In [46]:
Rios = {
...     'Leticia' : 'Amazonas',
...     'Montería': 'Sinu',
...     'Bogotá'  : 'Bogotá',
...     'San Gil': 'Fonce',
...     'Honda'  : 'Magladena'
... }

print(Rios)

{'Leticia': 'Amazonas', 'Montería': 'Sinu', 'Bogotá': 'Bogotá', 'San Gil': 'Fonce', 'Honda': 'Magladena'}


In [47]:
print(Rios['Montería'])

Sinu


También es posible crear un diccionario usando la función por defecto (built-in) `dict()`, usando una lista de tuplas:

In [48]:
my_dic=dict([
             ('Colores', ['Negro','Rojo','Azul']),
             ('Animales', 'Gato'),
             ('Calzado', ['Botas','Botines','Deportivos','Sanadalias'])
            ])

print(my_dic)

{'Colores': ['Negro', 'Rojo', 'Azul'], 'Animales': 'Gato', 'Calzado': ['Botas', 'Botines', 'Deportivos', 'Sanadalias']}


Veamos por ejemplo, los ítems que pertenecen a la llave **Colores**

In [49]:
print(my_dic['Colores'])


['Negro', 'Rojo', 'Azul']


Una vez ingresado a los ítem del diccionario, en caso de ser listas, podemos acceder a sus elementos tal cual lo hacemos con las listas (por sus índices)

In [50]:
print(my_dic['Colores'][1])

Rojo


In [51]:
print('Ví pasar un',my_dic['Animales'],'con',my_dic['Calzado'][0],'de color',my_dic['Colores'][0])

Ví pasar un Gato con Botas de color Negro


####  Manejo de diccionarios:

Podemos agregar, modificar y eliminar valores de un diccionario:

##### Agregar valores:

In [52]:
my_dic['Valor']=['20','50','12']
print(my_dic)

{'Colores': ['Negro', 'Rojo', 'Azul'], 'Animales': 'Gato', 'Calzado': ['Botas', 'Botines', 'Deportivos', 'Sanadalias'], 'Valor': ['20', '50', '12']}


##### Modificar valores:

In [53]:
my_dic['Colores']='Negro'
print(my_dic)

{'Colores': 'Negro', 'Animales': 'Gato', 'Calzado': ['Botas', 'Botines', 'Deportivos', 'Sanadalias'], 'Valor': ['20', '50', '12']}


##### Eliminar valores:

In [54]:
del my_dic['Valor']
print(my_dic)

{'Colores': 'Negro', 'Animales': 'Gato', 'Calzado': ['Botas', 'Botines', 'Deportivos', 'Sanadalias']}


Este concepto es muy importante, pues resalta la capacidad de un diccionario en incrementar su tamaño sin generar error:

In [55]:
#Generar diccionario vacío
persona = {}
print(type(persona))

# Agregar llaves y sus definiciones (items)
persona['Nombre'] = 'Gengis'
persona['Apellido'] = 'Khan'
persona['Edad'] = 23
persona['Esposa'] = ['Börte Qatun','Yesugen','Qulan Qatun','Möge Qatun','Juerbiesu','Ibaqa Beki']
persona['Hijos'] = 'En estudio'
persona['Mascotas'] = {'Perro': 'Wahadi', 'Gato': 'Gotze','Leon':'Pichirilo'}

print(persona)
print('Hijos de',persona['Nombre'],':',persona['Hijos'])

<class 'dict'>
{'Nombre': 'Gengis', 'Apellido': 'Khan', 'Edad': 23, 'Esposa': ['Börte Qatun', 'Yesugen', 'Qulan Qatun', 'Möge Qatun', 'Juerbiesu', 'Ibaqa Beki'], 'Hijos': 'En estudio', 'Mascotas': {'Perro': 'Wahadi', 'Gato': 'Gotze', 'Leon': 'Pichirilo'}}
Hijos de Gengis : En estudio


Del ejemplo anterior se puede observar que los diccionarios pueden contener diccionarios en su interior:

In [56]:
print(persona['Mascotas'])

{'Perro': 'Wahadi', 'Gato': 'Gotze', 'Leon': 'Pichirilo'}


In [57]:
print(persona['Mascotas']['Perro'])

Wahadi


### Métodos de los diccionarios

|Método|Descripción                  |
|---|---|
|clear()|Elimina todos los elementos del diccionario.|
|copy()|Devuelve una copia poco profunda del diccionario.|
|get(clave[,valor])|Devuelve el valor de la clave. Si no existe, devuelve el valor valor si se indica y si no, None.|
|items()|Devuelve una vista de los pares clave: valor del diccionario.|
|keys()|Devuelve una vista de las claves del diccionario.|
|pop(clave[,valor])|Devuelve el valor del elemento cuya clave es clave y elimina el elemento del diccionario. Si la clave no se encuentra, devuelve valor si se proporciona. Si la clave no se encuentra y no se indica valor, lanza la excepción KeyError.|
|popitem()|Devuelve un par (clave, valor) aleatorio del diccionario. Si el diccionario está vacío, lanza la excepción KeyError.|
|setdefault(clave[,valor])|Si la clave está en el diccionario, devuelve su valor. Si no lo está, inserta la clave con el valor valor y lo devuelve (si no se especifica valor, por defecto es None).|
|update(iterable)|Actualiza el diccionario con los pares clave: valor del iterable.|
|values()|Devuelve una vista de los valores del diccionario.|

# <span style="color:red"><center>numpy</center></span>

## ¿Qué es?

Numpy es un paquete de python dedicado principalmente al manejo de conjuntos o "arrays". Extendiendose luego al álgebra lineal, matrices y probabilidad.

### ¿Por qué usar arrays de numpy y no listas o tuplas de python?

Aunque python base tiene listas, el usar arrays es más rápido y consume menos memoria. Algo altamente necesario cuando se hacen operaciones de gran tamaño como puede ser el algebra matricial, por ejemplo.

In [58]:
import numpy as np

## Creación básica de arrays

Vamos a crear arrays de distintas dimensiones. Para esto podemos usar números, listas o tuplas.

In [59]:
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



Para revisar el número de dimensiones, usamos `ndim`

In [60]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Indexación básica

El proceso de indexación en numpy es similar al de las listas en python. Cada número implica buscar la posición en cada dimensión del array

In [61]:
print("a =",a)
print("b[2] = ",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])

a = 13
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


In [62]:
print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("d[1,0,2] =",d[1,0,2])

a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


Similarmente podemos segmentar **arrays** como en el las listas de python,

In [63]:
print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


## Diferentes tipos de datos en los arrays

Los arrays no están limitados a números enteros, pueden también tener cadenas, booleanos, o de punto flotante.

In [64]:
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)

<U7


Podemos manipular el tipo de los datos del array dentro de la función de creación del array `np.array`, siempre y cuando el cambio sea posible. Por ejemplo podemos pasar enteros a cadenas (integers a strings) pero no viceversa.

In [65]:
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [66]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i')
except:
    print("hay un error en su lógica")

hay un error en su lógica


Podemos también cambiar el tipo en arrays ya existentes

In [67]:
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante

int_array = floating_array.astype('i')
print(int_array)

[1 2 3]


## Forma de los arrays

La forma es distinta a la dimensión. Esta se define como el número de elementos de la dimensión. 

In [68]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


### Reformar arrays

Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión.

In [69]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [70]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


`d` es un array con 16 elementos, así que podemos hacer reshape con tamaños por ejemplo 1x16, 4x4, 8x2, 2x4x2 Por ejemplo, no podemos reformar un arrey a 3x5.

In [71]:
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

Hay un error en sus operaciones


In [72]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

### Dimensión desconocida

Podemos definir el cambio de forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de definir el tamaño que mejor se ajuste.

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos usar la dimensión desconocida para "aplanar" el array a una dimensión.

In [74]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Transpuesta

Para transponer el array utilizamos `.T`

In [75]:
print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Iterar arrays

Podemos usar los métodos tradicionales para iterar.

In [76]:
for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


Si queremos iterar cada elemento, necesitamos un `for` por cada dimensión

In [77]:
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


Esto por supuesto no es óptimo. Así que numpy tiene la función `nditer()` para estos casos.

In [78]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


## Aplicar operaciones entre arrays

*numpy* tiene sus propias formas de aplicar operaciones:

### Suma

*numpy* tiene dos funciones, `np.add()` y `np.sum()`. El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [79]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [80]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


Si aplicamos un eje en `np.sum()`, se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtienen los mismos resultados que `np.add()`

In [81]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [82]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

### Multiplicación

El primer caso de multiplicación es `np.prod()`, que funciona similar que `np.sum()`

In [83]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


### Multiplicación Matricial

Para la multiplicación de matrices usamos `np.matmul()` o `np.dot()`. hay que tener en cuenta la forma de las matrices

In [84]:
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [85]:
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan distinto con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [86]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

Con *matmul* no se pueden multiplicar escalares **c.A** (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con *dot*, donde este toma los números dentro de las matrices como elementos.

In [87]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])

# <span style="color:red"><center>Manejo de Datos en Pandas</center></span>

## **¿Qué es?**

Pandas es una librería de python destinada al análisis y manipulación de datos. Para obtener más información de ella, pueden revisar este [link](https://pandas.pydata.org/).

In [88]:
import pandas as pd

### **¿Cómo importar datos?**

Para leer los datos la estructura básica es *pd.read_tipo-archivo*. Si estamos en colab y queremos utilizar algunos datos que están en nuestro google drive podemos utilizar:


```
      from google.colab import drive
      drive.mount('/content/gdrive')
```

In [89]:
#from google.colab import ##drive correr solo en colab
#drive.mount('/content/gdrive')
counties= pd.read_excel("../datos/counties.xlsx")#cambiar dirección

Para tener una idea de qué variables y datos tengo en lo base de datos, sólo debemos llamarla.

In [90]:
counties

codestate  codecounty                 county  population         area
0             1        1001          Auta#%&()uga      54571.0   594.436000
1             1        1003   Baldwin#%&()  ?         182265.0  1589.784000
2             1        1005               Barbour      27457.0   884.876000
3             1        1007             Bi#%&()bb      22915.0   622.582000
4             1        1009         Blount  ?          57322.0   644.776000
...         ...         ...                    ...         ...          ...
3229         72       72151               Yabucoa      37941.0    55.215000
3230         72       72153                Ya_uco      42043.0    68.192000
3231         78       78010     ; St. Croix ?          50601.0    83.345868
3232         78       78020               St. John      4170.0    19.689867
3233         78       78030             St. Thomas     51634.0    31.313503

[3234 rows x 5 columns]

En lo anterior veiamos todas las variables con las 5 primeras y 5 últimas filas. Pero, podemos ver una cantidad  determinada de registros tanto del inicio de la tabla como del final. Utlizando *.head()* y *.tail()* respectivamente.

In [91]:
counties.head(3) #por defecto salen 5 primeros

codestate  codecounty                county  population      area
0          1        1001         Auta#%&()uga      54571.0   594.436
1          1        1003  Baldwin#%&()  ?         182265.0  1589.784
2          1        1005              Barbour      27457.0   884.876

In [92]:
counties.tail(2)

codestate  codecounty      county  population       area
3232         78       78020    St. John      4170.0  19.689867
3233         78       78030  St. Thomas     51634.0  31.313503

Si aparte de ver solamente la tabla, queremos más información de la base de datos, por ejemplo sus dimensiones y tipo de variables podemos  utilizar lo siguiente:

In [93]:
counties.info()
print("\n")
print("La forma de la base de datos es:",counties.shape)  #shape:forma de un array

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   codestate   3234 non-null   int64  
 1   codecounty  3234 non-null   int64  
 2   county      3234 non-null   object 
 3   population  3232 non-null   float64
 4   area        3234 non-null   float64
dtypes: float64(2), int64(2), object(1)
memory usage: 126.5+ KB


La forma de la base de datos es: (3234, 5)


In [94]:
print(counties.dtypes) #tipo de objeto en cada columna
print("\n")
print(counties.describe())
print("\n")
print(counties.describe(include="all")) #summary, si no se pone el include solo aparece de las variables numéricas

codestate       int64
codecounty      int64
county         object
population    float64
area          float64
dtype: object


         codestate    codecounty    population           area
count  3234.000000   3234.000000  3.232000e+03    3234.000000
mean     31.441868  31544.737786  9.679656e+04    1093.361817
std      16.411236  16425.545223  3.088044e+05    3564.706999
min       1.000000   1001.000000  1.700000e+01       0.031696
25%      19.000000  19039.500000  1.129700e+04     416.360000
50%      30.000000  30038.000000  2.607550e+04     602.977500
75%      46.000000  46128.500000  6.566050e+04     913.884500
max      78.000000  78030.000000  9.818605e+06  145504.789000


          codestate    codecounty    county    population           area
count   3234.000000   3234.000000      3234  3.232000e+03    3234.000000
unique          NaN           NaN      2625           NaN            NaN
top             NaN           NaN  Lincoln            NaN            NaN
freq            NaN   

### **Seleccionar subconjuntos de una base de datos**

### Escoger columnas

Para ver el nombre de las columnas que existen, podemos utilizar *.columns*.

In [95]:
counties.columns

Index(['codestate', 'codecounty', 'county', 'population', 'area'], dtype='object')

Escoger una columna específica o un conjunto de ellas

In [96]:
condado = counties["county"]

In [97]:
print(condado.shape) #array unidimensional con 3234 elementos
print(counties["county"].shape)
print(type(condado))

(3234,)
(3234,)
<class 'pandas.core.series.Series'>


In [98]:
codi_condado=counties[["codecounty","county"]]
print(codi_condado)
print(type(codi_condado))

      codecounty                 county
0           1001          Auta#%&()uga 
1           1003   Baldwin#%&()  ?     
2           1005               Barbour 
3           1007             Bi#%&()bb 
4           1009         Blount  ?     
...          ...                    ...
3229       72151               Yabucoa 
3230       72153                Ya_uco 
3231       78010     ; St. Croix ?     
3232       78020               St. John
3233       78030             St. Thomas

[3234 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


## Escoger filas

Podemos escoger ciertas filas a través de su posición. utilizando *.iloc*

In [99]:
from seaborn import load_dataset

In [100]:
print(counties.iloc[0:1,])
print(type(counties.iloc[0:1,]))

   codestate  codecounty         county  population     area
0          1        1001  Auta#%&()uga      54571.0  594.436
<class 'pandas.core.frame.DataFrame'>


In [101]:
print(counties.iloc[8:12,1:3])

    codecounty                 county
8         1017     ; Chambers  ?     
9         1019              Cherokee 
10        1021             ; Chilton 
11        1023               Choctaw 


O también escoger filas con base a alguna condicion o característica específica.

In [102]:
counties.tail()

codestate  codecounty                 county  population       area
3229         72       72151               Yabucoa      37941.0  55.215000
3230         72       72153                Ya_uco      42043.0  68.192000
3231         78       78010     ; St. Croix ?          50601.0  83.345868
3232         78       78020               St. John      4170.0  19.689867
3233         78       78030             St. Thomas     51634.0  31.313503

In [103]:
counties["codestate"] > 72 #Verdadero o falso si cumple la condición

0       False
1       False
2       False
3       False
4       False
        ...  
3229    False
3230    False
3231     True
3232     True
3233     True
Name: codestate, Length: 3234, dtype: bool

In [104]:
codsat72 = counties[counties["codestate"] > 72] # Llama aquellos cuyo valor es verdadero
codsat72.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 3231 to 3233
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   codestate   3 non-null      int64  
 1   codecounty  3 non-null      int64  
 2   county      3 non-null      object 
 3   population  3 non-null      float64
 4   area        3 non-null      float64
dtypes: float64(2), int64(2), object(1)
memory usage: 144.0+ bytes


## Manipulación datos textuales (Limpieza)

Para realizarle limpieza a columna *county* de la base de datos counties, podemos utilizar lo siguiente:

* **lower:**Poner en minúscula todo el texto.
* **replace:**Remplazar ciertos valores por otros.
* **strip:**Eliminar los espacios al principio y al final de la cadena.
* **title:**Poner primera letra de cada palabra en mayúscula.

In [105]:
counties["county"] = (counties["county"]
                            .str.lower()
                            .str.replace("[^a-záéíóúüñ ]","")
                            .str.replace(" +"," ")
                            .str.strip()
                            .str.title()
                           ) 

/tmp/ipykernel_36266/207899732.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  counties["county"] = (counties["county"]


In [106]:
print(counties)

      codestate  codecounty     county  population         area
0             1        1001    Autauga     54571.0   594.436000
1             1        1003    Baldwin    182265.0  1589.784000
2             1        1005    Barbour     27457.0   884.876000
3             1        1007       Bibb     22915.0   622.582000
4             1        1009     Blount     57322.0   644.776000
...         ...         ...        ...         ...          ...
3229         72       72151    Yabucoa     37941.0    55.215000
3230         72       72153      Yauco     42043.0    68.192000
3231         78       78010   St Croix     50601.0    83.345868
3232         78       78020    St John      4170.0    19.689867
3233         78       78030  St Thomas     51634.0    31.313503

[3234 rows x 5 columns]


## **Creación de columnas a partir de otras**

In [107]:
counties["densidad"]= counties["population"]/counties["area"]
print(counties[["densidad","population","area"]])

         densidad  population         area
0       91.802986     54571.0   594.436000
1      114.647650    182265.0  1589.784000
2       31.029206     27457.0   884.876000
3       36.806397     22915.0   622.582000
4       88.902192     57322.0   644.776000
...           ...         ...          ...
3229   687.150231     37941.0    55.215000
3230   616.538597     42043.0    68.192000
3231   607.120676     50601.0    83.345868
3232   211.784062      4170.0    19.689867
3233  1648.937201     51634.0    31.313503

[3234 rows x 3 columns]


### Renombrar columnas

In [108]:
print(counties.columns)
counties.rename(columns={"densidad":"densidad_pob"},inplace=True) #renombrar columna
print(counties.columns) #Verificación

Index(['codestate', 'codecounty', 'county', 'population', 'area', 'densidad'], dtype='object')
Index(['codestate', 'codecounty', 'county', 'population', 'area',
       'densidad_pob'],
      dtype='object')


### **Modificar tipo de dato de una columna**

In [109]:
print(counties.info())
print("\n")
counties["codestate"]=counties["codestate"].astype("float")
print(counties.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   codestate     3234 non-null   int64  
 1   codecounty    3234 non-null   int64  
 2   county        3234 non-null   object 
 3   population    3232 non-null   float64
 4   area          3234 non-null   float64
 5   densidad_pob  3232 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 151.7+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   codestate     3234 non-null   float64
 1   codecounty    3234 non-null   int64  
 2   county        3234 non-null   object 
 3   population    3232 non-null   float64
 4   area          3234 non-null   float64
 5   densidad_pob  3232 non-null   float64
dtypes: float64(4), int64(1),

### **Eliminar filas y columnas**

Eliminación filas, puede ser por posición o que cumpla una característica.

In [110]:
print(counties.shape)
counties = counties.drop(counties.iloc[0:3,].index)
counties = counties.drop(counties[counties['codecounty']==70].index)
print(counties.shape)

(3234, 6)
(3231, 6)


In [111]:
counties.drop(['densidad_pob'], axis=1,inplace=True) #inplace=True, para que me modifique la BD
counties.columns

Index(['codestate', 'codecounty', 'county', 'population', 'area'], dtype='object')

## Modificar tablas

es posible hacer cambios de orden y estructura en las tablas de pandas.

In [112]:
folder_path="/home/thejarmanitor/Documents/Jupyter/Curso-Basico-IA/datos/"

In [113]:
elections=pd.read_excel(folder_path+"elections.xlsx")
elections.head(5)

year  democrat  republic  other  codecounty
0  2000      4942     11993    273        1001
1  2000     13997     40872   1611        1003
2  2000      5188      5096    111        1005
3  2000      2710      4273    118        1007
4  2000      4977     12667    329        1009

organicemos los datos descendentemente depende de la cantidad de votos democratas

In [114]:
elections.sort_values(["democrat"], ascending=False)

year  democrat  republic   other  codecounty
12626  2016   2464364    769743  200201        6037
6400   2008   2295853    956425   65970        6037
9513   2012   2216903    885333   78831        6037
3287   2004   1907736   1076225   37686        6037
175    2000   1710505    871930  112719        6037
...     ...       ...       ...     ...         ...
11981  2012         9        54       1       48301
8852   2008         8       151       4       48269
11965  2012         5       139       1       48269
15078  2016         5       149       5       48269
15094  2016         4        58       3       48301

[15563 rows x 5 columns]

usando `groupby()` podemos juntar los datos por año y sumarlos para tener el total de votos por año

In [115]:
elections.groupby('year')[['democrat', 'republic']].sum()

democrat  republic
year                    
2000  50922964  50290498
2004  58614073  61603653
2008  69204582  59703000
2012  65508961  60460609
2016  65626398  62790289

Podemos aplicar ambos métodos en un mismo código

In [116]:
elections_sort=(elections.groupby('year')[['democrat', 'republic']]
                .sum()
                .sort_values('democrat', ascending=False))
display(elections_sort)

democrat  republic
year                    
2008  69204582  59703000
2016  65626398  62790289
2012  65508961  60460609
2004  58614073  61603653
2000  50922964  50290498

## Series  de tiempo y time stamps

Existe un tipo de datos llamado "timestamp" que se usa para medir registros de tiempo. Es posible pasar strings a este tipo de dato en diferentes formatos y trabajar con este usándolo como indice

In [117]:
airrpm=pd.read_csv(folder_path+'airrpm.txt', header=None, delimiter= '\s+', decimal=",")
airrpm.columns=["Time", "R1", "R2", "R3"]
airrpm.head()

Time     R1     R2     R3
0  Jan-79  26.64  15.50  11.15
1  Feb-79  27.20  16.58  10.62
2  Mar-79  27.87  18.85   9.02
3  Apr-79  23.22  17.23   5.99
4  May-79  23.27  16.04   7.23

La variable "Time" en este momento es un string. Pero podemos transformarlo usando `to_datetime()`. Para obtener más información de qué se podría poner en `format`, pueden revisar este [link](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior)

In [118]:
airrpm['Time']=pd.to_datetime(airrpm['Time'], format='%b-%y')
airrpm.index=airrpm['Time']
airrpm=airrpm.drop(['Time'], axis=1)
airrpm.head()

R1     R2     R3
Time                           
1979-01-01  26.64  15.50  11.15
1979-02-01  27.20  16.58  10.62
1979-03-01  27.87  18.85   9.02
1979-04-01  23.22  17.23   5.99
1979-05-01  23.27  16.04   7.23

Definiendo la fecha como índice, podemos extraer información con respecto al año y respecto al mes

In [119]:
airrpm.groupby([airrpm.index.month])['R1'].describe()

count       mean        std    min      25%    50%    75%    max
Time                                                                  
1      26.0  43.736538   9.778402  26.64  36.6575  44.82  51.86  59.36
2      25.0  43.680800   9.983696  27.20  35.5400  44.74  52.73  59.74
3      25.0  44.514400  10.363336  27.87  35.7000  45.01  53.26  60.10
4      25.0  44.287200  10.480331  23.22  36.6100  45.63  52.79  60.49
5      25.0  43.891600  10.524814  23.27  34.6000  45.11  52.57  60.36
6      25.0  45.655600  10.586951  27.30  35.4200  47.29  54.55  61.88
7      25.0  46.478400  10.333910  29.28  38.2700  47.79  54.94  63.02
8      25.0  46.773600  10.613169  27.27  38.8600  48.06  55.39  63.71
9      25.0  44.202400   9.731246  27.13  37.2600  46.39  51.83  59.54
10     25.0  44.433200  10.093832  26.97  37.8500  45.89  51.56  60.26
11     25.0  43.841200   9.923719  26.19  37.3300  45.50  51.02  59.21
12     25.0  44.600400   9.573277  27.32  38.7500  45.33  51.98  57.65

In [120]:
airrpm.groupby([airrpm.index.year]).sum().head(10)

R1      R2      R3
Time                        
1979  328.83  210.49  118.34
1980  340.95  200.92  140.05
1981  341.96  198.53  143.45
1982  355.17  210.23  144.91
1983  374.03  226.76  147.26
1984  415.88  243.71  172.18
1985  440.43  271.80  168.61
1986  492.37  302.20  190.18
1987  522.07  324.58  197.52
1988  530.25  328.69  201.57

# <span style="color:red"><center>Introducción al Procesamiento Paralelo<center></span>

<img src="http://dask.readthedocs.io/en/latest/_images/dask_horizontal.svg"
     align="right"
     width="30%"
     alt="Dask logo\">

# Paralelización con `dask.delayed`

En esta sección paralelizamos el código de estilo de ciclos de ejecución  con Dask y `dask.delayed`. A menudo, esta es la única función que necesitará para convertir funciones y usarlas con Dask.

Esta es una forma sencilla de usar `dask` para paralelizar bases de código existentes o construir [sistemas complejos] (https://blog.dask.org/2018/02/09/credit-models-with-dask). 

In [121]:
from dask.distributed import Client

client = Client(n_workers=4)

## <span style="color:blue">Bases</span>

Primero hagamos algunas funciones de juguete, `inc` y` add`, que duerman un rato para simular el trabajo. Luego, ejecutaremos estas funciones normalmente.

En la siguiente sección, paralelizaremos este código.

In [122]:
from time import sleep

def inc(x):
    sleep(1)
    return x+1

def add(x, y):
    sleep(1)
    return(x+y)


Calculamos el tiempo de ejecución de este código normal usando el comando mágico `%% time`, que es una función especial del Jupyter Notebook.

In [123]:
%%time
# esto debe tomar 3 segundos para correr debido a que
# llamamos cada función de manera secuencial, una después de la otra.

x = inc(1)
y = inc(3)
z = add(x, y)

CPU times: user 105 ms, sys: 24.1 ms, total: 129 ms
Wall time: 3 s


## <span style="color:blue">Paralelización usando dask.delayed</span>

Esas dos llamadas de incremento se pueden llamar en paralelo, porque son totalmente independientes entre sí.

Transformaremos las funciones *inc* y *add* usando la función `dask.delayed`. Cuando llamamos a la versión retrasada pasando los argumentos, exactamente como antes, la función original todavía no se llama, por lo que la ejecución de la celda finaliza muy rápidamente. En su lugar, se crea un objeto retrasado, que realiza un seguimiento de la función a llamar y los argumentos que se le pasan.

In [124]:
from dask import delayed

In [125]:
%%time

# Esto corre inmediatamente, todo lo que hace es construir un grafo
x = delayed(inc)(1)
y = delayed(inc)(2)
z = delayed(add)(x,y)

CPU times: user 553 µs, sys: 63 µs, total: 616 µs
Wall time: 458 µs


## <span style="color:blue">Cerrar el cliente</span>

Recuerden cerrar el cliente para acabar con el kernel y se recuperen los recursos del computador

In [126]:
client.close()